---
- name: Manage tower credential
  hosts: localhost
  
  tasks:
  - name: Add tower credential
    tower_credential:
      name: Workshop Credential
      organization: Default
      kind: ssh
      tower_username: admin
      tower_password: ansible
      
