---
- name: Manage tower credential
  hosts: all
  
  tasks:
  - name: Add tower credential
    tower_credential:
      name: {{name}}
      organization: Default
      kind: {{kind}}
      tower_username: {{tower_user}}
      tower_password: {{tower_password}}
      username: {{access_user}}
      password: {{access_password}}
      validate_certs: no      
