---
- name: Manage Tower inventory
  hosts: localhost
  become: yes

  tasks:
  - name: Add Tower Inventory
    tower_inventory:
      name: Workshop Inventory
      organization: Default
      tower_username: admin
      tower_password: ansible
      state: present
      validate_certs: no

  - name: Add Tower Inventory Host
    command: tower-manage inventory_import --group-filter web --source lab_inventory/hosts --inventory-name="Workshop Inventory"
