---
- name: Manage Tower Inventory Host
  hosts: localhost

  tasks:
  - name: Add Tower Inventory Host
    tower_job_template:
      name: Apache Install
      tower_username: admin
      tower_password: ansible
      job_type: run
      inventory: Workshop Inventory
      project: Ansible Workshop Examples
      playbook: rhel/apache/apache_install.yml
      credential: Workshop Credentials
      state: present
      become_enabled: yes
      validate_certs: no
